# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_interacctions.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user_interacctions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18user_interacctions.proto\x12\x0cinteractions\"\xb6\x01\n\x0fUserInfoRequest\x12\x1a\n\x08movie_id\x18\x01 \x01(\tR\x08movie_id\x12$\n\rwatching_time\x18\x02 \x01(\x02R\rwatching_time\x12(\n\x0fwatching_repeat\x18\x03 \x01(\x05R\x0fwatching_repeat\x12\x37\n\x0cinteractions\x18\x04 \x01(\x0b\x32!.interactions.InteractionsRequest\"K\n\x13InteractionsRequest\x12\r\n\x05genre\x18\x01 \x03(\t\x12\x13\n\x0bprotagonist\x18\x02 \x01(\t\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\"m\n\rMoviesRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x03(\t\x12\x13\n\x0bprotagonist\x18\x05 \x01(\t\x12\x10\n\x08\x64irector\x18\x06 \x01(\t\"\x81\x01\n\x17PreprocessedDataRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12+\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x1d.interactions.UserInfoRequest\x12+\n\x06movies\x18\x03 \x03(\x0b\x32\x1b.interactions.MoviesRequest\"\"\n\x0fSuccessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32j\n\x13InteractionsService\x12S\n\x0bProcessData\x12%.interactions.PreprocessedDataRequest\x1a\x1d.interactions.SuccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_interacctions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINFOREQUEST']._serialized_start=43
  _globals['_USERINFOREQUEST']._serialized_end=225
  _globals['_INTERACTIONSREQUEST']._serialized_start=227
  _globals['_INTERACTIONSREQUEST']._serialized_end=302
  _globals['_MOVIESREQUEST']._serialized_start=304
  _globals['_MOVIESREQUEST']._serialized_end=413
  _globals['_PREPROCESSEDDATAREQUEST']._serialized_start=416
  _globals['_PREPROCESSEDDATAREQUEST']._serialized_end=545
  _globals['_SUCCESSRESPONSE']._serialized_start=547
  _globals['_SUCCESSRESPONSE']._serialized_end=581
  _globals['_INTERACTIONSSERVICE']._serialized_start=583
  _globals['_INTERACTIONSSERVICE']._serialized_end=689
# @@protoc_insertion_point(module_scope)
